config/routes.rb
Rails.application.routes.draw do
  # get 'departments/index'
  # get 'departments/show'
  # get 'departments/new'
  # get 'departments/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "departments#index"
  resources :departments
  # resources :departments do
  #   resources :items
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  
  # before_action :set_department, only: [:show, :edit, :update, :destroy]
  
  # ---------------------------------------------------------------
  def index
    @departments = Department.all
    render :index 
  end

  def show
    @department = Department.find(params[:id])
  end
  # ---------------------------------------------------------------
  def new
    @department = Department.new
    render partial: "form"
    # The user fills in a form when het goes to the /departments/new   page. And when he presses "Create Department" it goes to the create method . the params are what the user inserted in the fields of the formk
    # as seen in the _form.html.erb,   the first field is placed in variable :name   and 2nd field  in variable  :acronym.   These 2 variables are really keys to the 'params'  hash which will be sent to the   department#create method

    # for the required fields, if the user doesn't place anything, and tries to submit, box appears saying "please fill out this field"
    # ??? So never goes to /views/departments/new.html.erb
  end

  def create 
    x = params.require(:department).permit(:name, :acronym)  # NOTE if dont put ':' --> undefined local variable or method 'acronym'
    # x = params.require(:department).permit(:name) --->   {"name"=> "Deli"}
    # Department.new(x)   ---> #<Department:0x00007f30bc4012a0 id: nil, name: "Deli", acronym: nil, created_at: nil, updated_at: nil>
    # so this has nil acronym , but to get both name AND acronym
    # --> <ActionController::Parameters {"name"=>"Deli", "acronym"=>"dl"} permitted: true>  
    # Department.
    @department = Department.new(x)
    
    if @department.save 
      # departments_path   -->  "/departments"
      # I think   @department.save   tries to save this new entry in to the table, and returns true if successful
      redirect_to departments_path  
    else
      render :new
    end
  end

  # ---------------------------------------------------------------
  def edit
    # binding.pry
    # params = {"controller"=>"departments", "action"=>"edit", "id"=>"3"}
    @department = Department.find(params[:id])
    render partial: "form"
  end

  def update
    # binding.pry 
    # When the user tries to 'edit' a department, and fills the form, and presses the 'Update department' button,
    # this function is called and a parameter is sent to it which is:
    # params = 
    #  {"_method"=>"patch", 
    #   "authenticity_token"=>"MKzquajH4Nsdwo+LR07eML9JjAdpKynmKbJg25pcNlkA+JgiCydzVfclJw7s2Pei9oW1cT9oxzp+EM+WK24PZQ==", 
    #   "department"=>{"name"=>"Electronics", "acronym"=>"Elx"}, 
    #   "commit"=>"Update Department", 
    #   "controller"=>"departments", 
    #   "action"=>"update", 
    #   "id"=>"1"}

    @department = Department.find(params[:id])
    x = params.require(:department).permit(:name, :acronym)
    if @department.update(x)
      redirect_to @department 
    else
      render :edit
    end
  end
  # ---------------------------------------------------------------
  def destroy
    @department = Department.find(params[:id])
    @department.delete
    # departments_path   -->  "/departments"
    redirect_to departments_path
  end

  # ---------------------------------------------------------------
  private
    def set_department
      @department = Repartment.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<!-- the form wants to receive @department. Thus both edit and new need to send @department variable to it -->
<!-- the new method creates an empty record thus its id value is nil. While the edit method  takes one entry of the table.  Which one ? well, it receives the params, and takes the id from it  (which is taken from the url the user puts in browser)  and finds the entry that will then send to the form.  In which case, the @department.id is NOT nil, so its true, so 'Edit Departmen' is shown. -->

<!-- I think the :name  and :acrony  s.how take value from the @department, thats why the form is already filled when you get to the form via 'edit'  and is empty when you get here via 'new' -->

<!-- how does the form button shows "create department" OR "update department"??? -->

<h1><%= @department.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<!-- form_for for --> 
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :acronym %>
  <%= f.text_field :acronym, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1> Welcome to the Department Listing </h1>
<ul>
  <% @departments.each do |dep| %> 
    <li> <%= link_to(dep.name, dep) %> </li>

    <!-- SAME THING:  <li> <%= link_to dep.name,  department_path(dep) %> </li> -->

  <% end %>
</ul>
<hr>
<!-- NOTICE that the '$ rails routes'  for going to /department/new   has the prefix 'new_department' , and that is the prefix to '_path' i think as I came up with  new_department_path below: -->
<%= link_to "Add a Department", new_department_path %>  

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h2> <%="Department:  " + @department.name + "(" + @department.acronym + ")" %> <h2>
<h4> <%= "Dep ID:" + @department.id.to_s  %> </h4>
<hr>

<%- # the following block is a comment block -%>


<!-- below,  edit_department_path(@department)  -- > departments/5/edit   -->
<%= link_to 'Edit Department', edit_department_path(@department) %>
<!-- below,    link_to '..' ,@department    -- >  department/6     or whatever department id -->
<%= link_to 'Delete department', @department, method: :delete  %>     <!-- # have send it 3rd argument method delete -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>